# Generated by Django 3.1.5 on 2023-03-11 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kategorimodel',
            table='blog_kategorimodel',
        ),
    ]
