# Generated by Django 3.1.5 on 2023-03-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_iletisimmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yorummodel',
            old_name='olusturma_Tarihi',
            new_name='olusturulma_Tarihi',
        ),
        migrations.RemoveField(
            model_name='yorummodel',
            name='guncellenme_Tarihi',
        ),
        migrations.AddField(
            model_name='yorummodel',
            name='duzenlenme_tarihi',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
